# --- COMMAND IDS ---
CMD_GET_TELEMETRY = 1
CMD_SET_TARGET_TEMP = 2
CMD_ENTER_DEBUG = 3
CMD_EXIT_DEBUG = 4
CMD_SELF_TEST = 5
CMD_OVERRIDE_PWM_DUTY = 6
CMD_CALIBRATE_PID = 7

_NO_ARG_COMMANDS = {
    CMD_GET_TELEMETRY,
    CMD_ENTER_DEBUG,
    CMD_EXIT_DEBUG,
    CMD_SELF_TEST,
    CMD_CALIBRATE_PID,
}

# --- SYSTEM STATES ---
SYSTEM_STATE_NORMAL = 0
SYSTEM_STATE_DEBUG_IDLE = 1
SYSTEM_STATE_SELF_TEST = 2
SYSTEM_STATE_PID_CAL = 3

# --- CBOR TELEMETRY MAP KEYS ---
TLM_KEY_TEMP = 1
TLM_KEY_RPM = 2
TLM_KEY_DUTY = 3
TLM_KEY_TARGET_TEMP = 4
TLM_KEY_SYSTEM_STATE = 5
