# --- Hardware Support ---
CONFIG_PWM=y
CONFIG_PWM_CAPTURE=y
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_FPU=y

# --- Floating Point Support for printk/LOG ---
CONFIG_CBPRINTF_FP_SUPPORT=y

# --- ZBus ---
CONFIG_ZBUS=y

# --- USB and UART CDC ACM config ---
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_PRODUCT="Fan Controller"
CONFIG_USB_DEVICE_PID=0x0001
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_LINE_CTRL=y