# --- Hardware Support ---
CONFIG_PWM=y
CONFIG_PWM_CAPTURE=y
CONFIG_I2C=y
CONFIG_SENSOR=y
CONFIG_FPU=y

# --- Floating Point Support for printk/LOG ---
CONFIG_CBPRINTF_FP_SUPPORT=y

# --- ZBus ---
CONFIG_ZBUS=y